### ISSUE TITLE
寻找一个稳定的亚洲服务器

### ISSUE THREAD

**Issue by kingdido999** [block-dog/news#5]
最好是Ubuntu系统 >= 16.04，我比较熟悉。

**Comment by summerhack** [comment]
打算使用Linode运营商，账户还在申请中。
目前使用了cloudcone，Ubuntu 16.04 LTS Server - 64 Bit，可以用作测试服。

**Comment by kingdido999** [comment]
@summerhack 账号申请下来了吗？
